name: Azure Static Web Apps CI/CD

on:
  push:
    branches-ignore:
      - main
    paths-ignore:
      - "infra/**"
      - ".github/workflows/terraform-*.yml"
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  build_job:
    uses: ./.github/workflows/reusables/swa-build.yml

  deploy_job:
    if: github.event_name == 'pull_request'
    needs: build_job
    uses: ./.github/workflows/reusables/swa-deploy.yml
    with:
      trigger_event: ${{ github.event_name }}
    secrets:
      AZURE_STATIC_WEB_APPS_API_TOKEN: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
