name: Azure Static Web Apps CI/CD

on:
  push:
    branches-ignore:
      - main
    paths-ignore:
      - "infra/**"
      - ".github/workflows/terraform-*.yml"
      - ".github/workflows/_terraform-*.yml"
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  build:
    name: Build SWA
    uses: ./.github/workflows/_swa-build.yml

  deploy:
    if: github.event_name == 'pull_request'
    needs: build
    name: Deploy SWA
    permissions:
      contents: read
      pull-requests: write
    uses: ./.github/workflows/_swa-deploy.yml
    with:
      trigger_event: ${{ github.event_name }}
    secrets:
      AZURE_STATIC_WEB_APPS_API_TOKEN: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
